### ISSUE TITLE
Halo MCC - "The Following Content is Not Installed" Error Message

### ISSUE THREAD

**Issue by mackieman123** [ZeroFox5866/nucleuscoop#28]
I have had an issue getting the Halo MCC to work using this application.

The problem occurs when I try to go on to the campaign missions, it gives the following message when I click in to the missions 

<img width="177" alt="bs 2" src="https://user-images.githubusercontent.com/78920711/107660498-412cc980-6c80-11eb-972a-3fa4cdc500bc.png">

We have all of the content downloaded as evidenced by the below screenshot. The content works fine when not being activated through nucleus (works on steam)

<img width="460" alt="bs 3" src="https://user-images.githubusercontent.com/78920711/107661185-f52e5480-6c80-11eb-8e24-a0c720377714.png">

We have tried numerous routes to fix this problem, including the following:
- turn off all antivirus
- run everything as admin
- downloaded all available DLCs (the games are considered DLCs as it lets you choose which content to have stored on your hard drive)
- given the nucleus folder full permissions [full control]
- redownloaded Nucleus numerous times

Further to this, we also receive the following error message when clicking the right arrow to enter the game setup within Nucleus (please see below)

<img width="226" alt="bs 1" src="https://user-images.githubusercontent.com/78920711/107660956-b00a2280-6c80-11eb-8fa8-5fb8a0e67635.png">

We have ensured that Nucleus is in the same drive as the game (C Drive) and have followed all setup instructions, reading all of the notes provided, but to no avail.

Any help and/or guidance to resolve this would be very much appreciated!

Also, thanks for doing something that 343 industries are clearly too lazy to do :)

**Comment by PotatoPope** [comment]
I have the same issue:

* I've installed Nucleus, put the folder in C:, the same driver as my game. 
* I've installed all the games in MC collection, I can start the campaigns by launching the game from Steam without Nucleus.
* Nucleus starts up fine, and starts two sessions of the game
* Both instances use LAN
* I can join Player 1s session
* I've disable all Anti-Virus
* I've given Nuclues fold full controll

It seems like the problem appears after both instances have been created, and hooks are about to be installed.

**Comment by PotatoPope** [comment]
Ok, it now works for me. I deleted the content of C:\Users\username\AppData\LocalLow\MCC

**Comment by mackieman123** [comment]
Just deleted the content of C:\Users\username\AppData\LocalLow\MCC. Same problem still occurring.

Thanks for the suggestion :)

**Comment by jeremybris** [comment]
@PotatoPope @mackieman123 

Hey, try this, it is an older version of the script:

https://drive.google.com/file/d/1CjMmRz7hb08YbfS9j7baq-IhY0zn9fb4/view?usp=sharing

Place it in your Nucleus Coop folder, in the scripts folder.

Also, please tell me if this works, because then we will know if there is a bug in the script.

**Comment by jeremybris** [comment]
Also, try this solution https://discord.com/channels/142649962839277568/142649962839277568/803460202497441802

**Comment by mackieman123** [comment]
Thanks Jeremybris for the suggestion, copying the older script into the directory worked!

The missions now load and the game is finally playable.

Closing the thread as the problem is now solved, hopefully this will help others with a similar issue

**Comment by jeremybris** [comment]
@mackieman123, @PotatoPope here is a preview for the latest build. It is supposed to fix this issue. Will you please try it and confirm: https://drive.google.com/drive/folders/1LMcQOiTjbIG9AykgP4pUSkRzP51-dZ1X?usp=sharing

"If you are still experiencing the missing content with this latest version, set these lines to false in the script: Game.UseNucleusEnvironment = 
Game.GoldbergNoLocalSave =
"

**Comment by JelledFro** [comment]
I have tried the two above scripts, the latest (updated a few days ago) and edited the two lines mentioned by  @jeremybris but still have this issue.

**Comment by jeremybris** [comment]
Are you on 1.1.3? And have you validated the integrity of your game files?

**Comment by JelledFro** [comment]
yes and yes

**Comment by jeremybris** [comment]
I don't know then. Try to put Halo on your C: drive and move the Nucleus Coop folder to different to different drives.
